nobel_fisica = {
    1901: {"ganador": "Wilhelm Conrad Röntgen", "logro": "Descubrimiento de los rayos X"},
    1902: {"ganador": "Hendrik Lorentz, Pieter Zeeman", "logro": "Descubrimiento del efecto Zeeman"},
    1903: {"ganador": "Antoine Henri Becquerel, Pierre Curie, Marie Curie", "logro": "Investigaciones sobre la radiación"},
    1904: {"ganador": "Lord Rayleigh (John William Strutt)", "logro": "Descubrimiento de la densidad de los gases y el descubrimiento del argón"},
    1905: {"ganador": "Philipp Eduard Anton von Lenard", "logro": "Investigaciones sobre los rayos catódicos"},
    1906: {"ganador": "Joseph John Thomson", "logro": "Descubrimiento del electrón"},
    1907: {"ganador": "Albert Abraham Michelson", "logro": "Mediciones precisas en espectroscopia"},
    1908: {"ganador": "Gabriel Lippmann", "logro": "Fotografía en color utilizando placas de interferencia"},
    1909: {"ganador": "Guglielmo Marconi, Karl Ferdinand Braun", "logro": "Desarrollo de la telegrafía inalámbrica"},
    1910: {"ganador": "Johannes Diderik van der Waals", "logro": "Ecuación de estado para gases y líquidos"},
    1911: {"ganador": "Wilhelm Wien", "logro": "Leyes del desplazamiento de Wien"},
    1912: {"ganador": "Nils Gustaf Dalén", "logro": "Válvulas solares y el regulador de presión para gas"},
    1913: {"ganador": "Heike Kamerlingh Onnes", "logro": "Liquefacción del helio"},
    1914: {"ganador": "Max von Laue", "logro": "Difracción de rayos X en cristales"},
    1915: {"ganador": "William Henry Bragg, William Lawrence Bragg", "logro": "Análisis de estructuras cristalinas mediante rayos X"},
    1917: {"ganador": "Charles Glover Barkla", "logro": "Retrodispersión de rayos X en gases"},
    1918: {"ganador": "Max Karl Ernst Ludwig Planck", "logro": "Leyes de la radiación térmica"},
    1919: {"ganador": "Johannes Stark", "logro": "Efecto Stark"},
    1920: {"ganador": "Charles Édouard Guillaume", "logro": "Descubrimiento de las aleaciones metálicas"},
    1921: {"ganador": "Albert Einstein", "logro": "Explicación del efecto fotoeléctrico"},
    1922: {"ganador": "Niels Bohr", "logro": "Estructura del átomo y la mecánica cuántica"},
    1923: {"ganador": "Robert Andrews Millikan", "logro": "Medición de la carga del electrón"},
    1924: {"ganador": "Manne Siegbahn", "logro": "Investigaciones sobre espectroscopia de rayos X"},
    1925: {"ganador": "James Franck, Gustav Hertz", "logro": "Impacto de electrones sobre átomos"},
    1926: {"ganador": "Jean Baptiste Perrin", "logro": "Estructura disociada de la materia"},
    1927: {"ganador": "Arthur Holly Compton", "logro": "Efecto Compton"},
    1928: {"ganador": "Owen Willans Richardson", "logro": "Efecto termoiónico"},
    1929: {"ganador": "Louis Victor Pierre Raymond, Comte de Broglie", "logro": "Teoría de la onda-materia"},
    1930: {"ganador": "C. V. Raman", "logro": "Efecto Raman"},
    1932: {"ganador": "Werner Karl Heisenberg", "logro": "Mecánica cuántica"},
    1933: {"ganador": "Erwin Schrödinger, Paul Dirac", "logro": "Desarrollo de la mecánica cuántica"},
    1935: {"ganador": "James Chadwick", "logro": "Descubrimiento del neutrón"},
    1936: {"ganador": "Victor Franz Hess, Carl David Anderson", "logro": "Descubrimiento de la radiación cósmica y el positrón"},
    1937: {"ganador": "Clinton Davisson, George Paget Thomson", "logro": "Difracción de electrones en cristales"},
    1938: {"ganador": "Enrico Fermi", "logro": "Creación de nuevos elementos"},
    1939: {"ganador": "Ernest Orlando Lawrence", "logro": "Desarrollo del ciclotrón"},
    1943: {"ganador": "Otto Stern", "logro": "Método de separación molecular"},
    1944: {"ganador": "Isidor Isaac Rabi", "logro": "Investigaciones en resonancia magnética"},
    1945: {"ganador": "Wolfgang Pauli", "logro": "Principio de exclusión de Pauli"},
    1946: {"ganador": "Percy Williams Bridgman", "logro": "Investigaciones sobre alta presión"},
    1947: {"ganador": "Edward Victor Appleton", "logro": "Investigaciones sobre la ionosfera"},
    1948: {"ganador": "Patrick Maynard Stuart Blackett", "logro": "Desarrollo de la cámara de burbujas"},
    1949: {"ganador": "Hideki Yukawa", "logro": "Teoría del mesón"},
    1950: {"ganador": "Cecil Frank Powell", "logro": "Desarrollo de la fotografía de emulsiones nucleares"},
    1951: {"ganador": "John Douglas Cockcroft, Ernest Thomas Sinton Walton", "logro": "Desarrollo de aceleradores de partículas"},
    1952: {"ganador": "Felix Bloch, Edward Mills Purcell", "logro": "Desarrollo de técnicas de resonancia magnética nuclear"},
    1953: {"ganador": "Frits Zernike", "logro": "Desarrollo del microscopio de fase"},
    1954: {"ganador": "Max Born, Walther Bothe", "logro": "Efectos de la probabilidad en la mecánica cuántica"},
    1955: {"ganador": "Willis Eugene Lamb, Polykarp Kusch", "logro": "Separación de líneas en el espectro del hidrógeno"},
    1956: {"ganador": "John Bardeen, Walter Houser Brattain, William Bradford Shockley", "logro": "Transistor"},
    1957: {"ganador": "Chen Ning Yang, Tsung-Dao Lee", "logro": "Violación de la paridad en la interacción débil"},
    1958: {"ganador": "Pavel Alekseyevich Cherenkov, Ilya Frank, Igor Y. Tamm", "logro": "Radiación Cherenkov"},
    1959: {"ganador": "Emilio Gino Segrè, Owen Chamberlain", "logro": "Antiprotón"},
    1960: {"ganador": "Donald Arthur Glaser", "logro": "Cámara de burbujas"},
    1961: {"ganador": "Robert Hofstadter, Rudolf Ludwig Mössbauer", "logro": "Dispersión de electrones en núcleos atómicos y resonancia de Mössbauer"},
    1962: {"ganador": "Lev Davidovich Landau", "logro": "Teoría de la superfluidez"},
    1963: {"ganador": "Eugene Paul Wigner, Maria Goeppert Mayer, J. Hans D. Jensen", "logro": "Modelo de capas nucleares y estructura del núcleo atómico"},
    1964: {"ganador": "Charles Hard Townes, Nicolay Gennadiyevich Basov, Aleksandr Prokhorov", "logro": "Desarrollo del láser y el maser"},
    1965: {"ganador": "Sin-Itiro Tomonaga, Julian Schwinger, Richard P. Feynman", "logro": "Electrodinámica cuántica"},
    1966: {"ganador": "Alfred Kastler", "logro": "Descubrimiento y desarrollo de métodos ópticos para estudios de resonancia en física atómica y molecular"},
    1967: {"ganador": "Hans Bethe", "logro": "Procesos nucleares en el sol"},
    1968: {"ganador": "Luis Walter Alvarez", "logro": "Desarrollo de técnicas de detección de partículas subatómicas"},
    1969: {"ganador": "Murray Gell-Mann", "logro": "Quarks y la teoría de la cromodinámica cuántica"},
    1970: {"ganador": "Hannes Alfvén, Louis Néel", "logro": "Magnetohidrodinámica y magnetismo de sólidos"},
    1971: {"ganador": "Dennis Gabor", "logro": "Holografía"},
    1972: {"ganador": "John Bardeen, Leon Neil Cooper, Robert Schrieffer", "logro": "Teoría de la superconductividad"},
    1973: {"ganador": "Leo Esaki, Ivar Giaever, Brian D. Josephson", "logro": "Efecto túnel en semiconductores y superconductores"},
    1974: {"ganador": "Martin Ryle, Antony Hewish", "logro": "Radioastronomía y descubrimiento de púlsares"},
    1975: {"ganador": "Aage Bohr, Ben Roy Mottelson, James Rainwater", "logro": "Modelo de capas nuclear y estructura nuclear"},
    1976: {"ganador": "Burton Richter, Samuel C.C. Ting", "logro": "Descubrimiento de partículas subatómicas"},
    1977: {"ganador": "Philip Warren Anderson, Sir Nevill Francis Mott, John Hasbrouck van Vleck", "logro": "Contribuciones a la teoría de estructura electrónica de materiales magnéticos y desordenados"},
    1978: {"ganador": "Pyotr Kapitsa, Arno Allan Penzias, Robert Woodrow Wilson", "logro": "Descubrimiento del efecto Josephson y la radiación cósmica de fondo en microondas"},
    1979: {"ganador": "Sheldon Lee Glashow, Abdus Salam, Steven Weinberg", "logro": "Unificación de las interacciones electromagnética y débil"},
    1980: {"ganador": "James Watson Cronin, Val Logsdon Fitch", "logro": "Violación de la simetría CP en la desintegración de partículas subatómicas"},
    1981: {"ganador": "Nicolaas Bloembergen, Arthur Leonard Schawlow, Kai M. Siegbahn", "logro": "Espectroscopia láser"},
    1982: {"ganador": "Kenneth G. Wilson", "logro": "Teoría de la transición de fase"},
    1983: {"ganador": "Subramanyan Chandrasekhar, William Alfred Fowler", "logro": "Teoría del destino final de las estrellas y los procesos nucleares en las estrellas"},
    1984: {"ganador": "Carlo Rubbia, Simon van der Meer", "logro": "Descubrimiento de las partículas W y Z"},
    1985: {"ganador": "Klaus von Klitzing", "logro": "Efecto Hall cuántico"},
    1986: {"ganador": "Ernst Ruska, Gerd Binnig, Heinrich Rohrer", "logro": "Desarrollo del microscopio de efecto túnel y el microscopio electrónico de barrido"},
    1987: {"ganador": "J. Georg Bednorz, K. Alex Müller", "logro": "Descubrimiento de superconductores de altas temperaturas"},
    1988: {"ganador": "Leon Max Lederman, Melvin Schwartz, Jack Steinberger", "logro": "Neutrinos"},
    1989: {"ganador": "Norman F. Ramsey, Hans G. Dehmelt, Wolfgang Paul", "logro": "Desarrollo de la espectroscopia de resonancia magnética"},
    1990: {"ganador": "Jerome I. Friedman, Henry W. Kendall, Richard E. Taylor", "logro": "Descubrimiento de los quarks"},
    1991: {"ganador": "Pierre-Gilles de Gennes", "logro": "Efectos de la materia condensada"},
    1992: {"ganador": "Georges Charpak", "logro": "Desarrollo de detectores de partículas"},
    1993: {"ganador": "Russell Alan Hulse, Joseph Hooton Taylor Jr.", "logro": "Descubrimiento de un sistema binario de púlsares"},
    1994: {"ganador": "Bertram N. Brockhouse, Clifford G. Shull", "logro": "Desarrollo de la técnica de dispersión de neutrones"},
    1995: {"ganador": "Martin L. Perl, Frederick Reines", "logro": "Descubrimiento de los neutrinos tau y del neutrino"},
    1996: {"ganador": "David M. Lee, Douglas D. Osheroff, Robert C. Richardson", "logro": "Superfluidos en helio-3"},
    1997: {"ganador": "Steven Chu, Claude Cohen-Tannoudji, William D. Phillips", "logro": "Enfriamiento y captura de átomos con láser"},
    1998: {"ganador": "Robert B. Laughlin, Horst L. Störmer, Daniel C. Tsui", "logro": "Efecto Hall cuántico fraccionario"},
    1999: {"ganador": "Gerardus 't Hooft, Martinus J.G. Veltman", "logro": "Formulación teórica de la electrodébil"},
    2000: {"ganador": "Zhores I. Alferov, Herbert Kroemer, Jack S. Kilby", "logro": "Desarrollo de dispositivos semiconductores"},
    2001: {"ganador": "Eric A. Cornell, Wolfgang Ketterle, Carl E. Wieman", "logro": "Condensados de Bose-Einstein"},
    2002: {"ganador": "Raymond Davis Jr., Masatoshi Koshiba, Riccardo Giacconi", "logro": "Observación cósmica de neutrinos y rayos X"},
    2003: {"ganador": "Alexei A. Abrikosov, Vitaly L. Ginzburg, Anthony J. Leggett", "logro": "Teorías sobre superconductividad y superfluidos"},
    2004: {"ganador": "David J. Gross, H. David Politzer, Frank Wilczek", "logro": "Libertad asintótica en la teoría de la interacción fuerte"},
    2005: {"ganador": "Roy J. Glauber, John L. Hall, Theodor W. Hänsch", "logro": "Desarrollo de métodos para estudios ópticos de alta precisión"},
    2006: {"ganador": "John C. Mather, George F. Smoot", "logro": "Descubrimiento de la radiación cósmica de fondo en microondas"},
    2007: {"ganador": "Albert Fert, Peter Grünberg", "logro": "Descubrimiento del efecto gigante de magnetorresistencia"},
    2008: {"ganador": "Yoichiro Nambu, Makoto Kobayashi, Toshihide Maskawa", "logro": "Origen del rompimiento de la simetría de la masa"},
    2009: {"ganador": "Charles K. Kao, Willard S. Boyle, George E. Smith", "logro": "Desarrollo de fibras ópticas y CCD"},
    2010: {"ganador": "Andre Geim, Konstantin Novoselov", "logro": "Descubrimiento del grafeno"},
    2011: {"ganador": "Saul Perlmutter, Brian P. Schmidt, Adam G. Riess", "logro": "Descubrimiento de la expansión acelerada del universo a través de supernovas"},
    2012: {"ganador": "Serge Haroche, David J. Wineland", "logro": "Control de sistemas cuánticos individuales"},
    2013: {"ganador": "François Englert, Peter W. Higgs", "logro": "Descubrimiento del bosón de Higgs"},
    2014: {"ganador": "Isamu Akasaki, Hiroshi Amano, Shuji Nakamura", "logro": "Desarrollo de diodos emisores de luz azul"},
    2015: {"ganador": "Takaaki Kajita, Arthur B. McDonald", "logro": "Descubrimiento de oscilaciones de neutrinos, que muestra que tienen masa"},
    2016: {"ganador": "David J. Thouless, F. Duncan M. Haldane, J. Michael Kosterlitz", "logro": "Teoría topológica de la materia exótica"},
    2017: {"ganador": "Rainer Weiss, Barry C. Barish, Kip S. Thorne", "logro": "Detectores LIGO y observación de ondas gravitacionales"},
    2018: {"ganador": "Arthur Ashkin, Gérard Mourou, Donna Strickland", "logro": "Pinzas ópticas y pulsos láser ultracortos"},
    2019: {"ganador": "James Peebles, Michel Mayor, Didier Queloz", "logro": "Contribuciones a nuestra comprensión del universo y descubrimiento de un exoplaneta en órbita"},
    2020: {"ganador": "Roger Penrose, Reinhard Genzel, Andrea Ghez", "logro": "Descubrimiento de agujeros negros y su formación en el universo"},
    2021: {"ganador": "Syukuro Manabe, Klaus Hasselmann, Giorgio Parisi", "logro": "Modelos físicos del clima terrestre, métodos computacionales avanzados en física"},
    2022: {"ganador": "Alain Aspect, John F. Clauser, Anton Zeilinger", "logro": "Experimentos sobre la paradoja EPR y las desigualdades de Bell"},
    2023: {"ganador": "Anne L’Huillier, Pierre Agostini, Ferenc Krausz", "logro": "Pulsos de luz de attosegundos para el estudio de la dinámica de los electrones en la materia"}
}
